sit:
  AUDIT_SOURCE_DATASET_ENABLED: true
  AWS_ACCOUNT_ID: 998343784597
  STACK_NAME_PREFIX: ""
  AUDIT_EMAIL_FROM: "GeoPlatform Notice <no-reply@geoplatform.info>"
  AUDIT_EMAIL_LIST: fgdc-qaqc@xentity.com
  AUDIT_EXTRA_FIELDS: false
  AUDIT_REPORT_FUNCTION: ${self:provider.stage}-Messaging
  AUTHENTICATION_URL: "https://stg-accounts.geoplatform.gov/auth/token"
  CATALOG_BASE_URL: "https://catalog.data.gov/dataset/"
  CATALOG_API_URL: "https://catalog.data.gov/api/3/action/package_show?id="
  CATALOG_API_PACKAGE_SEARCH_URL: "https://catalog.data.gov/api/3/action/package_search?rows=1&q=name:"
  CATALOG_API_ROOT: https://catalog.data.gov/api/3/action
  CKAN_TO_CSV_ENABLED: true
  CONFIG_BUCKET: ${self:custom.environment.DEPLOYMENT_BUCKET_PREFIX}-${self:provider.stage}-${self:provider.region}-public-configs
  DEPLOYMENT_BUCKET_PREFIX: ${self:custom.namespaceShort}
  DETECT_NGDA_CHANGES_ENABLED: false
  EXTRACT_METADATA_FROM_DATA_GOV_ENABLED: true
  GEONETWORK_API: https://${self:provider.stage}-geonetwork.geoplatform.info/geonetwork/srv
  GEONETWORK4_API: https://${self:provider.stage}-geonetwork4.geoplatform.info/geonetwork/srv
  GEONETWORK_VALIDATE_RECORDS_AT_IMPORT: true
  GEOPLATFORM_PORTAL_HOSTNAME: ${self:provider.stage}.geoplatform.info
  GEOSERVER_BASE_URL: https://${self:provider.stage}-geoserver.geoplatform.info
  GP_CORE_LAYER_VERSION: arn:aws:lambda:${self:provider.region}:${aws:accountId}:layer:GPCore:317
  GP_DATASET_BASE_URL: "http://www.geoplatform.gov/id/dataset/"
  GP_DATASETS_BASE_URL: "https://www.geoplatform.gov/resources/datasets"
  HARVEST_BASE_URL: "https://catalog.data.gov/harvest/object/"
  HARVEST_BUCKET: ${self:custom.environment.DEPLOYMENT_BUCKET_PREFIX}-${self:provider.stage}-${self:provider.region}-magic-fgdc
  HARVEST_DB_NAME: magic_harvest
  HARVEST_QUERY_URL: datasets?q="Metadata Record in Data.gov Catalog"&size=2000
  HARVEST_TYPE: regp
  MAXIMUM_MESSAGE_SIZE: 4096
  MESSAGING_FUNCTION: ${self:provider.stage}-Messaging
  MESSAGING_BUCKET: ${self:custom.environment.DEPLOYMENT_BUCKET_PREFIX}-${self:provider.stage}-${self:provider.region}-messaging-bucket
  NGDA_HARVEST_DB_NAME: magic_harvest
  NUMBER_OF_LAMBDA_VERSIONS_TO_RETAIN: 3
  PROCESS_SERVICES_BUCKET: ${self:custom.environment.DEPLOYMENT_BUCKET_PREFIX}-${self:provider.stage}-${self:provider.region}-process-services
  PROCESS_SERVICES_ROUTING: populate_services_routing.json
  PYGEOAPI_CONFIG: /mnt/efs/pygeoapi/default.config.yml
  REGPADMIN: ${self:provider.stage}/geoplatform/admin-credentials
  REGP_BASE_URL: "https://ual.geoplatform.gov/api"
  REGP_URL: "https://stg-ual.geoplatform.gov/api"
  REPORT_BUCKET: ${self:custom.environment.DEPLOYMENT_BUCKET_PREFIX}-${self:provider.stage}-${self:provider.region}-report-bucket
  REPORT_SYSTEM_STATS_ENABLED: true
  SPATIAL_ARTIFACT_BUCKET: ${self:custom.environment.DEPLOYMENT_BUCKET_PREFIX}-${self:provider.stage}-${self:provider.region}-geoplatform-archive
  TERRIAMAP_CATALOG_BUCKET: ${self:custom.environment.DEPLOYMENT_BUCKET_PREFIX}-${self:provider.stage}-${self:provider.region}-terriamap-catalog
  TILEGARDEN_CONFIG_BUCKET: ${self:custom.environment.DEPLOYMENT_BUCKET_PREFIX}-${self:provider.stage}-tileservice-configurations
  TILEGARDEN_DB_NAME: tilegarden
  TILEGARDEN_PRECACHING_ENABLED: "true"
  TILEGARDEN_URL: https://${self:provider.stage}-tileservice.geoplatform.info
  UPDATE_LMT_NGDA_ENABLED: true
  DB_BACKUP_BUCKET: ${self:custom.environment.DEPLOYMENT_BUCKET_PREFIX}-${self:provider.stage}-${self:provider.region}-database-backups
  OPENSEARCH_INDEX_NAME: gp-records-v1 # version our index for more seamless migrations
  OPENSEARCH_DOMAIN: opensearch

stg:
  AUDIT_SOURCE_DATASET_ENABLED: true
  AWS_ACCOUNT_ID: 824888059401
  STACK_NAME_PREFIX: "${self:custom.namespaceShort}-"
  AUDIT_EMAIL_FROM: "GeoPlatform Notice <no-reply@geoplatform.gov>"
  AUDIT_EMAIL_LIST: fgdc-qaqc@xentity.com
  AUDIT_EXTRA_FIELDS: false
  AUDIT_REPORT_FUNCTION: ${self:provider.stage}-Messaging
  AUTHENTICATION_URL: "https://stg-accounts.geoplatform.gov/auth/token"
  CATALOG_BASE_URL: https://catalog.data.gov/dataset/
  CATALOG_API_URL: https://catalog.data.gov/api/3/action/package_show?id=
  CATALOG_API_PACKAGE_SEARCH_URL: "https://catalog.data.gov/api/3/action/package_search?rows=1&q=name:"
  CATALOG_API_ROOT: https://catalog.data.gov/api/3/action
  CKAN_TO_CSV_ENABLED: false
  CONFIG_BUCKET: ${self:custom.environment.DEPLOYMENT_BUCKET_PREFIX}-${self:provider.stage}-${self:provider.region}-public-configs
  DEPLOYMENT_BUCKET_PREFIX: ${self:custom.namespaceShort}
  DETECT_NGDA_CHANGES_ENABLED: false
  EXTRACT_METADATA_FROM_DATA_GOV_ENABLED: true
  GEONETWORK_API: https://${self:provider.stage}-geonetwork.geoplatform.info/geonetwork/srv
  GEONETWORK4_API: https://${self:provider.stage}-geonetwork4.geoplatform.info/geonetwork/srv
  GEONETWORK_VALIDATE_RECORDS_AT_IMPORT: true
  GEOPLATFORM_PORTAL_HOSTNAME: ${self:provider.stage}.geoplatform.gov
  GEOSERVER_BASE_URL: https://${self:provider.stage}-geoserver.geoplatform.gov
  GP_CORE_LAYER_VERSION: arn:aws:lambda:${self:provider.region}:${aws:accountId}:layer:GPCore:196
  GP_DATASET_BASE_URL: "http://www.geoplatform.gov/id/dataset/"
  GP_DATASETS_BASE_URL: "https://www.geoplatform.gov/resources/datasets"
  HARVEST_BASE_URL: https://catalog.data.gov/harvest/object/
  HARVEST_BUCKET: ${self:custom.environment.DEPLOYMENT_BUCKET_PREFIX}-${self:provider.stage}-${self:provider.region}-magic-fgdc
  HARVEST_DB_NAME: magic_harvest
  HARVEST_QUERY_URL: datasets?q="Metadata Record in Data.gov Catalog"&size=2000
  HARVEST_TYPE: regp
  MAXIMUM_MESSAGE_SIZE: 4096
  MESSAGING_FUNCTION: ${self:provider.stage}-Messaging
  MESSAGING_BUCKET: ${self:custom.environment.DEPLOYMENT_BUCKET_PREFIX}-${self:provider.stage}-${self:provider.region}-messaging-bucket
  NGDA_HARVEST_DB_NAME: magic_harvest
  NUMBER_OF_LAMBDA_VERSIONS_TO_RETAIN: 3
  PROCESS_SERVICES_BUCKET: ${self:custom.environment.DEPLOYMENT_BUCKET_PREFIX}-${self:provider.stage}-${self:provider.region}-process-services
  PROCESS_SERVICES_ROUTING: populate_services_routing.json
  PYGEOAPI_CONFIG: /mnt/efs/pygeoapi/default.config.yml
  REGPADMIN: ${self:provider.stage}/geoplatform/admin-credentials
  REGP_BASE_URL: https://ual.geoplatform.gov/api
  REGP_URL: "https://stg-ual.geoplatform.gov/api"
  REPORT_BUCKET: ${self:custom.environment.DEPLOYMENT_BUCKET_PREFIX}-${self:provider.stage}-${self:provider.region}-report-bucket
  REPORT_SYSTEM_STATS_ENABLED: true
  SPATIAL_ARTIFACT_BUCKET: ${self:custom.environment.DEPLOYMENT_BUCKET_PREFIX}-${self:provider.stage}-${self:provider.region}-geoplatform-archive
  TERRIAMAP_CATALOG_BUCKET: ${self:custom.environment.DEPLOYMENT_BUCKET_PREFIX}-${self:provider.stage}-${self:provider.region}-terriamap-catalog
  TILEGARDEN_CONFIG_BUCKET: ${self:custom.environment.DEPLOYMENT_BUCKET_PREFIX}-${self:provider.stage}-tileservice-configurations
  TILEGARDEN_DB_NAME: tilegarden
  TILEGARDEN_PRECACHING_ENABLED: "true"
  TILEGARDEN_URL: https://${self:provider.stage}-tileservice.geoplatform.gov
  UPDATE_LMT_NGDA_ENABLED: true
  DB_BACKUP_BUCKET: ${self:custom.environment.DEPLOYMENT_BUCKET_PREFIX}-${self:provider.stage}-${self:provider.region}-database-backups

prd:
  AUDIT_SOURCE_DATASET_ENABLED: true
  AWS_ACCOUNT_ID: 824888059401
  STACK_NAME_PREFIX: "${self:custom.namespaceShort}-"
  AUDIT_EMAIL_FROM: "GeoPlatform Notice <no-reply@geoplatform.gov>"
  AUDIT_EMAIL_LIST: metadata-audit-report@xentity.com
  AUDIT_EXTRA_FIELDS: false
  AUDIT_REPORT_FUNCTION: ${self:provider.stage}-Messaging
  AUTHENTICATION_URL: "https://accounts.geoplatform.gov/auth/token"
  CATALOG_BASE_URL: https://catalog.data.gov/dataset/
  CATALOG_API_URL: https://catalog.data.gov/api/3/action/package_show?id=
  CATALOG_API_PACKAGE_SEARCH_URL: "https://catalog.data.gov/api/3/action/package_search?rows=1&q=name:"
  CATALOG_API_ROOT: https://catalog.data.gov/api/3/action
  CKAN_TO_CSV_ENABLED: false
  CONFIG_BUCKET: ${self:custom.environment.DEPLOYMENT_BUCKET_PREFIX}-${self:provider.stage}-${self:provider.region}-public-configs
  DEPLOYMENT_BUCKET_PREFIX: ${self:custom.namespaceShort}
  DETECT_NGDA_CHANGES_ENABLED: false
  EXTRACT_METADATA_FROM_DATA_GOV_ENABLED: true
  GEONETWORK_API: https://geonetwork.geoplatform.gov/geonetwork/srv
  GEONETWORK4_API: https://geonetwork4.geoplatform.gov/geonetwork/srv
  GEONETWORK_VALIDATE_RECORDS_AT_IMPORT: true
  GEOPLATFORM_PORTAL_HOSTNAME: beta.geoplatform.gov
  GEOSERVER_BASE_URL: https://geoserver.geoplatform.gov
  GP_CORE_LAYER_VERSION: arn:aws:lambda:${self:provider.region}:${aws:accountId}:layer:GPCore:196
  GP_DATASET_BASE_URL: "http://www.geoplatform.gov/id/dataset/"
  GP_DATASETS_BASE_URL: "https://www.geoplatform.gov/resources/datasets"
  HARVEST_BASE_URL: https://catalog.data.gov/harvest/object/
  HARVEST_BUCKET: ${self:custom.environment.DEPLOYMENT_BUCKET_PREFIX}-${self:provider.stage}-${self:provider.region}-magic-fgdc
  HARVEST_DB_NAME: magic_harvest
  HARVEST_QUERY_URL: datasets?q="Metadata Record in Data.gov Catalog"&size=2000
  HARVEST_TYPE: regp
  MAXIMUM_MESSAGE_SIZE: 4096
  MESSAGING_FUNCTION: ${self:provider.stage}-Messaging
  MESSAGING_BUCKET: ${self:custom.environment.DEPLOYMENT_BUCKET_PREFIX}-${self:provider.stage}-${self:provider.region}-messaging-bucket
  NGDA_HARVEST_DB_NAME: magic_harvest
  NUMBER_OF_LAMBDA_VERSIONS_TO_RETAIN: 5
  PROCESS_SERVICES_BUCKET: ${self:custom.environment.DEPLOYMENT_BUCKET_PREFIX}-${self:provider.stage}-${self:provider.region}-process-services
  PROCESS_SERVICES_ROUTING: populate_services_routing.json
  PYGEOAPI_CONFIG: /mnt/efs/pygeoapi/default.config.yml
  REGPADMIN: ${self:provider.stage}/geoplatform/admin-credentials
  REGP_BASE_URL: https://ual.geoplatform.gov/api
  REGP_URL: "https://stg-ual.geoplatform.gov/api"
  REPORT_BUCKET: ${self:custom.environment.DEPLOYMENT_BUCKET_PREFIX}-${self:provider.stage}-${self:provider.region}-report-bucket
  REPORT_SYSTEM_STATS_ENABLED: true
  SPATIAL_ARTIFACT_BUCKET: ${self:custom.environment.DEPLOYMENT_BUCKET_PREFIX}-${self:provider.stage}-${self:provider.region}-geoplatform-archive
  TERRIAMAP_CATALOG_BUCKET: ${self:custom.environment.DEPLOYMENT_BUCKET_PREFIX}-${self:provider.stage}-${self:provider.region}-terriamap-catalog
  TILEGARDEN_CONFIG_BUCKET: ${self:custom.environment.DEPLOYMENT_BUCKET_PREFIX}-${self:provider.stage}-tileservice-configurations
  TILEGARDEN_DB_NAME: tilegarden
  TILEGARDEN_PRECACHING_ENABLED: "true"
  TILEGARDEN_URL: https://tileservice.geoplatform.gov
  UPDATE_LMT_NGDA_ENABLED: true
  DB_BACKUP_BUCKET: ${self:custom.environment.DEPLOYMENT_BUCKET_PREFIX}-${self:provider.stage}-${self:provider.region}-database-backups
